apiVersion: v1
kind: Service
metadata:
  labels:
    app: atst
  name: postgres-loadbalancer
  namespace: atat
spec:
  selector:
    app: postgres-database
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432